doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL)%'
            old:
                # configure these for your database server
                url: 'mysql://root:root@127.0.0.1:3306/tour_agency' 
                driver: 'pdo_mysql'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true      
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware  
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                dql:
                    datetime_functions:
                        second: DoctrineExtensions\Query\Postgresql\Second
                        minute: DoctrineExtensions\Query\Postgresql\Minute
                        hour: DoctrineExtensions\Query\Postgresql\Hour
                        day: DoctrineExtensions\Query\Postgresql\Day
                        month: DoctrineExtensions\Query\Postgresql\Month
                        year: DoctrineExtensions\Query\Postgresql\Year
                        date_format: DoctrineExtensions\Query\Postgresql\DateFormat
                        at_time_zone: DoctrineExtensions\Query\Postgresql\AtTimeZoneFunction
                        date_part: DoctrineExtensions\Query\Postgresql\DatePart
                        extract: DoctrineExtensions\Query\Postgresql\ExtractFunction
                        date_trunc: DoctrineExtensions\Query\Postgresql\DateTrunc
                        date: DoctrineExtensions\Query\Postgresql\Date

                    string_functions:
                        str_to_date: DoctrineExtensions\Query\Postgresql\StrToDate
                        count_filter: DoctrineExtensions\Query\Postgresql\CountFilterFunction
                        string_agg: DoctrineExtensions\Query\Postgresql\StringAgg
                        greatest: DoctrineExtensions\Query\Postgresql\Greatest
                        least: DoctrineExtensions\Query\Postgresql\Least
                        regexp_replace: DoctrineExtensions\Query\Postgresql\RegexpReplace        
            old:
                connection: old
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware  
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/EntityOld/Old'
                        prefix: 'App\EntityOld\Old'
                        alias: old                   
        
