<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220720170224 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE activity_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE activity_combo_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE booking_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE booking_accommodation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE booking_house_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE booking_house_room_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE booking_transfer_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE destination_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE driver_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE guide_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE house_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE house_feature_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE house_room_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE house_room_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE house_season_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE house_season_room_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE house_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE itinerary_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE itinerary_day_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE itinerary_day_template_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE itinerary_template_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE location_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE location_distance_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE notification_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE notification_tour_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE notification_tour_template_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE province_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE service_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE sleeping_requirement_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE srroom_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tour_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE tour_template_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE transportation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE transportation_price_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE transportation_route_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE activity (id INT NOT NULL, destination_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, person_cost SMALLINT DEFAULT NULL, guide_cost SMALLINT DEFAULT NULL, car_cost SMALLINT DEFAULT NULL, person_per_car SMALLINT DEFAULT NULL, type VARCHAR(10) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AC74095A816C6140 ON activity (destination_id)');
        $this->addSql('CREATE TABLE activity_combo (id INT NOT NULL, activity_id INT NOT NULL, parent_id INT NOT NULL, priority SMALLINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AF3E06F981C06096 ON activity_combo (activity_id)');
        $this->addSql('CREATE INDEX IDX_AF3E06F9727ACA70 ON activity_combo (parent_id)');
        $this->addSql('CREATE TABLE booking (id INT NOT NULL, sleeping_requirement_id INT DEFAULT NULL, tour_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, pax SMALLINT DEFAULT NULL, lp SMALLINT DEFAULT NULL, note TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E00CEDDEAE2DDF69 ON booking (sleeping_requirement_id)');
        $this->addSql('CREATE INDEX IDX_E00CEDDE15ED8D43 ON booking (tour_id)');
        $this->addSql('CREATE TABLE booking_accommodation (id INT NOT NULL, booking_id INT NOT NULL, itinerary_id INT DEFAULT NULL, date_in DATE DEFAULT NULL, date_out DATE DEFAULT NULL, canceled BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_260114D23301C60 ON booking_accommodation (booking_id)');
        $this->addSql('CREATE INDEX IDX_260114D215F737B2 ON booking_accommodation (itinerary_id)');
        $this->addSql('CREATE TABLE booking_house (id INT NOT NULL, house_id INT DEFAULT NULL, booking_accommodation_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F6A9C4286BB74515 ON booking_house (house_id)');
        $this->addSql('CREATE INDEX IDX_F6A9C428B1E5C38B ON booking_house (booking_accommodation_id)');
        $this->addSql('CREATE TABLE booking_house_room (id INT NOT NULL, house_room_id INT NOT NULL, booking_house_id INT NOT NULL, price SMALLINT DEFAULT NULL, cant SMALLINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B36B1CC0C0C0F68E ON booking_house_room (house_room_id)');
        $this->addSql('CREATE INDEX IDX_B36B1CC05083DB98 ON booking_house_room (booking_house_id)');
        $this->addSql('CREATE TABLE booking_transfer (id INT NOT NULL, destination_id INT DEFAULT NULL, driver_id INT DEFAULT NULL, booking_in_id INT DEFAULT NULL, booking_out_id INT DEFAULT NULL, tour_id INT DEFAULT NULL, contact VARCHAR(255) DEFAULT NULL, persons SMALLINT DEFAULT NULL, date DATE DEFAULT NULL, hour TIME(0) WITHOUT TIME ZONE DEFAULT NULL, flight_data VARCHAR(255) DEFAULT NULL, price SMALLINT DEFAULT NULL, from_hour TIME(0) WITHOUT TIME ZONE DEFAULT NULL, to_hour TIME(0) WITHOUT TIME ZONE DEFAULT NULL, charge SMALLINT DEFAULT NULL, sent BOOLEAN DEFAULT NULL, canceled BOOLEAN DEFAULT NULL, note TEXT DEFAULT NULL, type VARCHAR(3) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7B003D4D816C6140 ON booking_transfer (destination_id)');
        $this->addSql('CREATE INDEX IDX_7B003D4DC3423909 ON booking_transfer (driver_id)');
        $this->addSql('CREATE INDEX IDX_7B003D4D81858386 ON booking_transfer (booking_in_id)');
        $this->addSql('CREATE INDEX IDX_7B003D4DBF956384 ON booking_transfer (booking_out_id)');
        $this->addSql('CREATE INDEX IDX_7B003D4D15ED8D43 ON booking_transfer (tour_id)');
        $this->addSql('CREATE TABLE booking_transfer_house (booking_transfer_id INT NOT NULL, house_id INT NOT NULL, PRIMARY KEY(booking_transfer_id, house_id))');
        $this->addSql('CREATE INDEX IDX_5F3E373574EB9366 ON booking_transfer_house (booking_transfer_id)');
        $this->addSql('CREATE INDEX IDX_5F3E37356BB74515 ON booking_transfer_house (house_id)');
        $this->addSql('CREATE TABLE destination (id INT NOT NULL, province_id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3EC63EAAE946114A ON destination (province_id)');
        $this->addSql('CREATE TABLE driver (id INT NOT NULL, name VARCHAR(255) NOT NULL, phone VARCHAR(50) DEFAULT NULL, pax SMALLINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE guide (id INT NOT NULL, name VARCHAR(30) NOT NULL, last_name VARCHAR(30) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, bonus SMALLINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE house (id INT NOT NULL, type_id INT DEFAULT NULL, destination_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_67D5399DC54C8C93 ON house (type_id)');
        $this->addSql('CREATE INDEX IDX_67D5399D816C6140 ON house (destination_id)');
        $this->addSql('CREATE TABLE house_house_feature (house_id INT NOT NULL, house_feature_id INT NOT NULL, PRIMARY KEY(house_id, house_feature_id))');
        $this->addSql('CREATE INDEX IDX_4B7736006BB74515 ON house_house_feature (house_id)');
        $this->addSql('CREATE INDEX IDX_4B773600174F074 ON house_house_feature (house_feature_id)');
        $this->addSql('CREATE TABLE house_feature (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE house_room (id INT NOT NULL, room_type_id INT NOT NULL, house_id INT DEFAULT NULL, price SMALLINT DEFAULT NULL, cant SMALLINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2AF17FB1296E3073 ON house_room (room_type_id)');
        $this->addSql('CREATE INDEX IDX_2AF17FB16BB74515 ON house_room (house_id)');
        $this->addSql('CREATE TABLE house_room_type (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE house_season (id INT NOT NULL, house_id INT NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4359C2206BB74515 ON house_season (house_id)');
        $this->addSql('CREATE TABLE house_season_room (id INT NOT NULL, room_id INT NOT NULL, house_season_id INT NOT NULL, price SMALLINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8A0621F054177093 ON house_season_room (room_id)');
        $this->addSql('CREATE INDEX IDX_8A0621F0B577DF0F ON house_season_room (house_season_id)');
        $this->addSql('CREATE TABLE house_type (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE itinerary (id INT NOT NULL, destination_id INT DEFAULT NULL, house_id INT DEFAULT NULL, tour_id INT NOT NULL, days SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FF2238F6816C6140 ON itinerary (destination_id)');
        $this->addSql('CREATE INDEX IDX_FF2238F66BB74515 ON itinerary (house_id)');
        $this->addSql('CREATE INDEX IDX_FF2238F615ED8D43 ON itinerary (tour_id)');
        $this->addSql('CREATE TABLE itinerary_day (id INT NOT NULL, itinerary_id INT NOT NULL, no_guide BOOLEAN DEFAULT NULL, day SMALLINT DEFAULT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AB0E649415F737B2 ON itinerary_day (itinerary_id)');
        $this->addSql('CREATE TABLE itinerary_day_activity (itinerary_day_id INT NOT NULL, activity_id INT NOT NULL, PRIMARY KEY(itinerary_day_id, activity_id))');
        $this->addSql('CREATE INDEX IDX_62886B397A725613 ON itinerary_day_activity (itinerary_day_id)');
        $this->addSql('CREATE INDEX IDX_62886B3981C06096 ON itinerary_day_activity (activity_id)');
        $this->addSql('CREATE TABLE itinerary_day_template (id INT NOT NULL, itinerary_id INT NOT NULL, no_guide BOOLEAN DEFAULT NULL, day SMALLINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_599C7DE015F737B2 ON itinerary_day_template (itinerary_id)');
        $this->addSql('CREATE TABLE itinerary_day_template_activity (itinerary_day_template_id INT NOT NULL, activity_id INT NOT NULL, PRIMARY KEY(itinerary_day_template_id, activity_id))');
        $this->addSql('CREATE INDEX IDX_8C3E0CE7AC8BCD1D ON itinerary_day_template_activity (itinerary_day_template_id)');
        $this->addSql('CREATE INDEX IDX_8C3E0CE781C06096 ON itinerary_day_template_activity (activity_id)');
        $this->addSql('CREATE TABLE itinerary_template (id INT NOT NULL, destination_id INT DEFAULT NULL, house_id INT DEFAULT NULL, tour_template_id INT NOT NULL, days SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B6822B42816C6140 ON itinerary_template (destination_id)');
        $this->addSql('CREATE INDEX IDX_B6822B426BB74515 ON itinerary_template (house_id)');
        $this->addSql('CREATE INDEX IDX_B6822B42658C5D7B ON itinerary_template (tour_template_id)');
        $this->addSql('CREATE TABLE location (id INT NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE location_distance (id INT NOT NULL, location1_id INT NOT NULL, location2_id INT NOT NULL, kms SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CDC7B863DC6ACE95 ON location_distance (location1_id)');
        $this->addSql('CREATE INDEX IDX_CDC7B863CEDF617B ON location_distance (location2_id)');
        $this->addSql('CREATE TABLE notification (id INT NOT NULL, name VARCHAR(255) NOT NULL, icon VARCHAR(50) DEFAULT NULL, days SMALLINT DEFAULT NULL, priority SMALLINT DEFAULT 0, slug VARCHAR(50) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE notification_service (notification_id INT NOT NULL, service_id INT NOT NULL, PRIMARY KEY(notification_id, service_id))');
        $this->addSql('CREATE INDEX IDX_F4831065EF1A9D84 ON notification_service (notification_id)');
        $this->addSql('CREATE INDEX IDX_F4831065ED5CA9E6 ON notification_service (service_id)');
        $this->addSql('CREATE TABLE notification_tour (id INT NOT NULL, tour_id INT NOT NULL, notification_id INT NOT NULL, days SMALLINT NOT NULL, complete BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D2EDB25315ED8D43 ON notification_tour (tour_id)');
        $this->addSql('CREATE INDEX IDX_D2EDB253EF1A9D84 ON notification_tour (notification_id)');
        $this->addSql('CREATE TABLE notification_tour_template (id INT NOT NULL, tour_template_id INT NOT NULL, notification_id INT NOT NULL, days SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5B2D8C79658C5D7B ON notification_tour_template (tour_template_id)');
        $this->addSql('CREATE INDEX IDX_5B2D8C79EF1A9D84 ON notification_tour_template (notification_id)');
        $this->addSql('CREATE TABLE province (id INT NOT NULL, name VARCHAR(20) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE service (id INT NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(10) DEFAULT NULL, days_to_show INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE sleeping_requirement (id INT NOT NULL, accommodation_type_id INT DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_413AD3EA8978F869 ON sleeping_requirement (accommodation_type_id)');
        $this->addSql('CREATE TABLE srroom_type (id INT NOT NULL, room_type_id INT DEFAULT NULL, sleeping_requirement_id INT NOT NULL, cant SMALLINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F7287958296E3073 ON srroom_type (room_type_id)');
        $this->addSql('CREATE INDEX IDX_F7287958AE2DDF69 ON srroom_type (sleeping_requirement_id)');
        $this->addSql('CREATE TABLE tour (id INT NOT NULL, guide_id INT DEFAULT NULL, transfer_in_id INT DEFAULT NULL, transfer_out_id INT DEFAULT NULL, transportation_id INT DEFAULT NULL, house_type_id INT DEFAULT NULL, template_id INT DEFAULT NULL, service_id INT DEFAULT NULL, code VARCHAR(30) DEFAULT NULL, guide_wage DOUBLE PRECISION DEFAULT NULL, color VARCHAR(10) DEFAULT NULL, start_place VARCHAR(255) DEFAULT NULL, finish_place VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, bonus SMALLINT DEFAULT NULL, days SMALLINT DEFAULT NULL, start_day SMALLINT DEFAULT NULL, agent BOOLEAN DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, canceled BOOLEAN DEFAULT NULL, name VARCHAR(255) NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6AD1F96977153098 ON tour (code)');
        $this->addSql('CREATE INDEX IDX_6AD1F969D7ED1D4B ON tour (guide_id)');
        $this->addSql('CREATE INDEX IDX_6AD1F969B37D8B6B ON tour (transfer_in_id)');
        $this->addSql('CREATE INDEX IDX_6AD1F969611C0549 ON tour (transfer_out_id)');
        $this->addSql('CREATE INDEX IDX_6AD1F969F7BB88E4 ON tour (transportation_id)');
        $this->addSql('CREATE INDEX IDX_6AD1F969519B0A8E ON tour (house_type_id)');
        $this->addSql('CREATE INDEX IDX_6AD1F9695DA0FB8 ON tour (template_id)');
        $this->addSql('CREATE INDEX IDX_6AD1F969ED5CA9E6 ON tour (service_id)');
        $this->addSql('CREATE TABLE tour_activity (tour_id INT NOT NULL, activity_id INT NOT NULL, PRIMARY KEY(tour_id, activity_id))');
        $this->addSql('CREATE INDEX IDX_368B506915ED8D43 ON tour_activity (tour_id)');
        $this->addSql('CREATE INDEX IDX_368B506981C06096 ON tour_activity (activity_id)');
        $this->addSql('CREATE TABLE tour_template (id INT NOT NULL, template1_id INT DEFAULT NULL, template2_id INT DEFAULT NULL, transfer_in_id INT DEFAULT NULL, transfer_out_id INT DEFAULT NULL, transportation_id INT DEFAULT NULL, house_type_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(30) DEFAULT NULL, type VARCHAR(50) DEFAULT NULL, tour_type VARCHAR(5) DEFAULT NULL, guide_wage DOUBLE PRECISION DEFAULT NULL, color VARCHAR(10) DEFAULT NULL, start_place VARCHAR(255) DEFAULT NULL, finish_place VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, bonus SMALLINT DEFAULT NULL, days SMALLINT DEFAULT NULL, start_day SMALLINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D9F46B077153098 ON tour_template (code)');
        $this->addSql('CREATE INDEX IDX_D9F46B013D3CC22 ON tour_template (template1_id)');
        $this->addSql('CREATE INDEX IDX_D9F46B016663CC ON tour_template (template2_id)');
        $this->addSql('CREATE INDEX IDX_D9F46B0B37D8B6B ON tour_template (transfer_in_id)');
        $this->addSql('CREATE INDEX IDX_D9F46B0611C0549 ON tour_template (transfer_out_id)');
        $this->addSql('CREATE INDEX IDX_D9F46B0F7BB88E4 ON tour_template (transportation_id)');
        $this->addSql('CREATE INDEX IDX_D9F46B0519B0A8E ON tour_template (house_type_id)');
        $this->addSql('CREATE TABLE tour_template_activity (tour_template_id INT NOT NULL, activity_id INT NOT NULL, PRIMARY KEY(tour_template_id, activity_id))');
        $this->addSql('CREATE INDEX IDX_803C52C6658C5D7B ON tour_template_activity (tour_template_id)');
        $this->addSql('CREATE INDEX IDX_803C52C681C06096 ON tour_template_activity (activity_id)');
        $this->addSql('CREATE TABLE transportation (id INT NOT NULL, driver_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9B1722DC3423909 ON transportation (driver_id)');
        $this->addSql('CREATE TABLE transportation_price (id INT NOT NULL, transportation_id INT DEFAULT NULL, min SMALLINT NOT NULL, max SMALLINT NOT NULL, price DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D2CF7972F7BB88E4 ON transportation_price (transportation_id)');
        $this->addSql('CREATE TABLE transportation_route (id INT NOT NULL, location_from_id INT DEFAULT NULL, location_to_id INT NOT NULL, transportation_id INT DEFAULT NULL, kms SMALLINT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1AC37BD2968BCAAF ON transportation_route (location_from_id)');
        $this->addSql('CREATE INDEX IDX_1AC37BD246690F40 ON transportation_route (location_to_id)');
        $this->addSql('CREATE INDEX IDX_1AC37BD2F7BB88E4 ON transportation_route (transportation_id)');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095A816C6140 FOREIGN KEY (destination_id) REFERENCES destination (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE activity_combo ADD CONSTRAINT FK_AF3E06F981C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE activity_combo ADD CONSTRAINT FK_AF3E06F9727ACA70 FOREIGN KEY (parent_id) REFERENCES activity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEAE2DDF69 FOREIGN KEY (sleeping_requirement_id) REFERENCES sleeping_requirement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE15ED8D43 FOREIGN KEY (tour_id) REFERENCES tour (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking_accommodation ADD CONSTRAINT FK_260114D23301C60 FOREIGN KEY (booking_id) REFERENCES booking (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking_accommodation ADD CONSTRAINT FK_260114D215F737B2 FOREIGN KEY (itinerary_id) REFERENCES itinerary (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking_house ADD CONSTRAINT FK_F6A9C4286BB74515 FOREIGN KEY (house_id) REFERENCES house (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking_house ADD CONSTRAINT FK_F6A9C428B1E5C38B FOREIGN KEY (booking_accommodation_id) REFERENCES booking_accommodation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking_house_room ADD CONSTRAINT FK_B36B1CC0C0C0F68E FOREIGN KEY (house_room_id) REFERENCES house_room (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking_house_room ADD CONSTRAINT FK_B36B1CC05083DB98 FOREIGN KEY (booking_house_id) REFERENCES booking_house (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking_transfer ADD CONSTRAINT FK_7B003D4D816C6140 FOREIGN KEY (destination_id) REFERENCES destination (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking_transfer ADD CONSTRAINT FK_7B003D4DC3423909 FOREIGN KEY (driver_id) REFERENCES driver (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking_transfer ADD CONSTRAINT FK_7B003D4D81858386 FOREIGN KEY (booking_in_id) REFERENCES booking (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking_transfer ADD CONSTRAINT FK_7B003D4DBF956384 FOREIGN KEY (booking_out_id) REFERENCES booking (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking_transfer ADD CONSTRAINT FK_7B003D4D15ED8D43 FOREIGN KEY (tour_id) REFERENCES tour (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking_transfer_house ADD CONSTRAINT FK_5F3E373574EB9366 FOREIGN KEY (booking_transfer_id) REFERENCES booking_transfer (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE booking_transfer_house ADD CONSTRAINT FK_5F3E37356BB74515 FOREIGN KEY (house_id) REFERENCES house (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE destination ADD CONSTRAINT FK_3EC63EAAE946114A FOREIGN KEY (province_id) REFERENCES province (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE house ADD CONSTRAINT FK_67D5399DC54C8C93 FOREIGN KEY (type_id) REFERENCES house_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE house ADD CONSTRAINT FK_67D5399D816C6140 FOREIGN KEY (destination_id) REFERENCES destination (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE house_house_feature ADD CONSTRAINT FK_4B7736006BB74515 FOREIGN KEY (house_id) REFERENCES house (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE house_house_feature ADD CONSTRAINT FK_4B773600174F074 FOREIGN KEY (house_feature_id) REFERENCES house_feature (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE house_room ADD CONSTRAINT FK_2AF17FB1296E3073 FOREIGN KEY (room_type_id) REFERENCES house_room_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE house_room ADD CONSTRAINT FK_2AF17FB16BB74515 FOREIGN KEY (house_id) REFERENCES house (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE house_season ADD CONSTRAINT FK_4359C2206BB74515 FOREIGN KEY (house_id) REFERENCES house (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE house_season_room ADD CONSTRAINT FK_8A0621F054177093 FOREIGN KEY (room_id) REFERENCES house_room (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE house_season_room ADD CONSTRAINT FK_8A0621F0B577DF0F FOREIGN KEY (house_season_id) REFERENCES house_season (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE itinerary ADD CONSTRAINT FK_FF2238F6816C6140 FOREIGN KEY (destination_id) REFERENCES destination (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE itinerary ADD CONSTRAINT FK_FF2238F66BB74515 FOREIGN KEY (house_id) REFERENCES house (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE itinerary ADD CONSTRAINT FK_FF2238F615ED8D43 FOREIGN KEY (tour_id) REFERENCES tour (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE itinerary_day ADD CONSTRAINT FK_AB0E649415F737B2 FOREIGN KEY (itinerary_id) REFERENCES itinerary (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE itinerary_day_activity ADD CONSTRAINT FK_62886B397A725613 FOREIGN KEY (itinerary_day_id) REFERENCES itinerary_day (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE itinerary_day_activity ADD CONSTRAINT FK_62886B3981C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE itinerary_day_template ADD CONSTRAINT FK_599C7DE015F737B2 FOREIGN KEY (itinerary_id) REFERENCES itinerary_template (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE itinerary_day_template_activity ADD CONSTRAINT FK_8C3E0CE7AC8BCD1D FOREIGN KEY (itinerary_day_template_id) REFERENCES itinerary_day_template (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE itinerary_day_template_activity ADD CONSTRAINT FK_8C3E0CE781C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE itinerary_template ADD CONSTRAINT FK_B6822B42816C6140 FOREIGN KEY (destination_id) REFERENCES destination (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE itinerary_template ADD CONSTRAINT FK_B6822B426BB74515 FOREIGN KEY (house_id) REFERENCES house (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE itinerary_template ADD CONSTRAINT FK_B6822B42658C5D7B FOREIGN KEY (tour_template_id) REFERENCES tour_template (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE location_distance ADD CONSTRAINT FK_CDC7B863DC6ACE95 FOREIGN KEY (location1_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE location_distance ADD CONSTRAINT FK_CDC7B863CEDF617B FOREIGN KEY (location2_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification_service ADD CONSTRAINT FK_F4831065EF1A9D84 FOREIGN KEY (notification_id) REFERENCES notification (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification_service ADD CONSTRAINT FK_F4831065ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification_tour ADD CONSTRAINT FK_D2EDB25315ED8D43 FOREIGN KEY (tour_id) REFERENCES tour (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification_tour ADD CONSTRAINT FK_D2EDB253EF1A9D84 FOREIGN KEY (notification_id) REFERENCES notification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification_tour_template ADD CONSTRAINT FK_5B2D8C79658C5D7B FOREIGN KEY (tour_template_id) REFERENCES tour_template (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification_tour_template ADD CONSTRAINT FK_5B2D8C79EF1A9D84 FOREIGN KEY (notification_id) REFERENCES notification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE sleeping_requirement ADD CONSTRAINT FK_413AD3EA8978F869 FOREIGN KEY (accommodation_type_id) REFERENCES house_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE srroom_type ADD CONSTRAINT FK_F7287958296E3073 FOREIGN KEY (room_type_id) REFERENCES house_room_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE srroom_type ADD CONSTRAINT FK_F7287958AE2DDF69 FOREIGN KEY (sleeping_requirement_id) REFERENCES sleeping_requirement (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tour ADD CONSTRAINT FK_6AD1F969D7ED1D4B FOREIGN KEY (guide_id) REFERENCES guide (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tour ADD CONSTRAINT FK_6AD1F969B37D8B6B FOREIGN KEY (transfer_in_id) REFERENCES destination (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tour ADD CONSTRAINT FK_6AD1F969611C0549 FOREIGN KEY (transfer_out_id) REFERENCES destination (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tour ADD CONSTRAINT FK_6AD1F969F7BB88E4 FOREIGN KEY (transportation_id) REFERENCES transportation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tour ADD CONSTRAINT FK_6AD1F969519B0A8E FOREIGN KEY (house_type_id) REFERENCES house_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tour ADD CONSTRAINT FK_6AD1F9695DA0FB8 FOREIGN KEY (template_id) REFERENCES tour_template (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tour ADD CONSTRAINT FK_6AD1F969ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tour_activity ADD CONSTRAINT FK_368B506915ED8D43 FOREIGN KEY (tour_id) REFERENCES tour (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tour_activity ADD CONSTRAINT FK_368B506981C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tour_template ADD CONSTRAINT FK_D9F46B013D3CC22 FOREIGN KEY (template1_id) REFERENCES tour_template (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tour_template ADD CONSTRAINT FK_D9F46B016663CC FOREIGN KEY (template2_id) REFERENCES tour_template (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tour_template ADD CONSTRAINT FK_D9F46B0B37D8B6B FOREIGN KEY (transfer_in_id) REFERENCES destination (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tour_template ADD CONSTRAINT FK_D9F46B0611C0549 FOREIGN KEY (transfer_out_id) REFERENCES destination (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tour_template ADD CONSTRAINT FK_D9F46B0F7BB88E4 FOREIGN KEY (transportation_id) REFERENCES transportation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tour_template ADD CONSTRAINT FK_D9F46B0519B0A8E FOREIGN KEY (house_type_id) REFERENCES house_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tour_template_activity ADD CONSTRAINT FK_803C52C6658C5D7B FOREIGN KEY (tour_template_id) REFERENCES tour_template (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tour_template_activity ADD CONSTRAINT FK_803C52C681C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE transportation ADD CONSTRAINT FK_9B1722DC3423909 FOREIGN KEY (driver_id) REFERENCES driver (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE transportation_price ADD CONSTRAINT FK_D2CF7972F7BB88E4 FOREIGN KEY (transportation_id) REFERENCES transportation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE transportation_route ADD CONSTRAINT FK_1AC37BD2968BCAAF FOREIGN KEY (location_from_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE transportation_route ADD CONSTRAINT FK_1AC37BD246690F40 FOREIGN KEY (location_to_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE transportation_route ADD CONSTRAINT FK_1AC37BD2F7BB88E4 FOREIGN KEY (transportation_id) REFERENCES transportation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE activity_combo DROP CONSTRAINT FK_AF3E06F981C06096');
        $this->addSql('ALTER TABLE activity_combo DROP CONSTRAINT FK_AF3E06F9727ACA70');
        $this->addSql('ALTER TABLE itinerary_day_activity DROP CONSTRAINT FK_62886B3981C06096');
        $this->addSql('ALTER TABLE itinerary_day_template_activity DROP CONSTRAINT FK_8C3E0CE781C06096');
        $this->addSql('ALTER TABLE tour_activity DROP CONSTRAINT FK_368B506981C06096');
        $this->addSql('ALTER TABLE tour_template_activity DROP CONSTRAINT FK_803C52C681C06096');
        $this->addSql('ALTER TABLE booking_accommodation DROP CONSTRAINT FK_260114D23301C60');
        $this->addSql('ALTER TABLE booking_transfer DROP CONSTRAINT FK_7B003D4D81858386');
        $this->addSql('ALTER TABLE booking_transfer DROP CONSTRAINT FK_7B003D4DBF956384');
        $this->addSql('ALTER TABLE booking_house DROP CONSTRAINT FK_F6A9C428B1E5C38B');
        $this->addSql('ALTER TABLE booking_house_room DROP CONSTRAINT FK_B36B1CC05083DB98');
        $this->addSql('ALTER TABLE booking_transfer_house DROP CONSTRAINT FK_5F3E373574EB9366');
        $this->addSql('ALTER TABLE activity DROP CONSTRAINT FK_AC74095A816C6140');
        $this->addSql('ALTER TABLE booking_transfer DROP CONSTRAINT FK_7B003D4D816C6140');
        $this->addSql('ALTER TABLE house DROP CONSTRAINT FK_67D5399D816C6140');
        $this->addSql('ALTER TABLE itinerary DROP CONSTRAINT FK_FF2238F6816C6140');
        $this->addSql('ALTER TABLE itinerary_template DROP CONSTRAINT FK_B6822B42816C6140');
        $this->addSql('ALTER TABLE tour DROP CONSTRAINT FK_6AD1F969B37D8B6B');
        $this->addSql('ALTER TABLE tour DROP CONSTRAINT FK_6AD1F969611C0549');
        $this->addSql('ALTER TABLE tour_template DROP CONSTRAINT FK_D9F46B0B37D8B6B');
        $this->addSql('ALTER TABLE tour_template DROP CONSTRAINT FK_D9F46B0611C0549');
        $this->addSql('ALTER TABLE booking_transfer DROP CONSTRAINT FK_7B003D4DC3423909');
        $this->addSql('ALTER TABLE transportation DROP CONSTRAINT FK_9B1722DC3423909');
        $this->addSql('ALTER TABLE tour DROP CONSTRAINT FK_6AD1F969D7ED1D4B');
        $this->addSql('ALTER TABLE booking_house DROP CONSTRAINT FK_F6A9C4286BB74515');
        $this->addSql('ALTER TABLE booking_transfer_house DROP CONSTRAINT FK_5F3E37356BB74515');
        $this->addSql('ALTER TABLE house_house_feature DROP CONSTRAINT FK_4B7736006BB74515');
        $this->addSql('ALTER TABLE house_room DROP CONSTRAINT FK_2AF17FB16BB74515');
        $this->addSql('ALTER TABLE house_season DROP CONSTRAINT FK_4359C2206BB74515');
        $this->addSql('ALTER TABLE itinerary DROP CONSTRAINT FK_FF2238F66BB74515');
        $this->addSql('ALTER TABLE itinerary_template DROP CONSTRAINT FK_B6822B426BB74515');
        $this->addSql('ALTER TABLE house_house_feature DROP CONSTRAINT FK_4B773600174F074');
        $this->addSql('ALTER TABLE booking_house_room DROP CONSTRAINT FK_B36B1CC0C0C0F68E');
        $this->addSql('ALTER TABLE house_season_room DROP CONSTRAINT FK_8A0621F054177093');
        $this->addSql('ALTER TABLE house_room DROP CONSTRAINT FK_2AF17FB1296E3073');
        $this->addSql('ALTER TABLE srroom_type DROP CONSTRAINT FK_F7287958296E3073');
        $this->addSql('ALTER TABLE house_season_room DROP CONSTRAINT FK_8A0621F0B577DF0F');
        $this->addSql('ALTER TABLE house DROP CONSTRAINT FK_67D5399DC54C8C93');
        $this->addSql('ALTER TABLE sleeping_requirement DROP CONSTRAINT FK_413AD3EA8978F869');
        $this->addSql('ALTER TABLE tour DROP CONSTRAINT FK_6AD1F969519B0A8E');
        $this->addSql('ALTER TABLE tour_template DROP CONSTRAINT FK_D9F46B0519B0A8E');
        $this->addSql('ALTER TABLE booking_accommodation DROP CONSTRAINT FK_260114D215F737B2');
        $this->addSql('ALTER TABLE itinerary_day DROP CONSTRAINT FK_AB0E649415F737B2');
        $this->addSql('ALTER TABLE itinerary_day_activity DROP CONSTRAINT FK_62886B397A725613');
        $this->addSql('ALTER TABLE itinerary_day_template_activity DROP CONSTRAINT FK_8C3E0CE7AC8BCD1D');
        $this->addSql('ALTER TABLE itinerary_day_template DROP CONSTRAINT FK_599C7DE015F737B2');
        $this->addSql('ALTER TABLE location_distance DROP CONSTRAINT FK_CDC7B863DC6ACE95');
        $this->addSql('ALTER TABLE location_distance DROP CONSTRAINT FK_CDC7B863CEDF617B');
        $this->addSql('ALTER TABLE transportation_route DROP CONSTRAINT FK_1AC37BD2968BCAAF');
        $this->addSql('ALTER TABLE transportation_route DROP CONSTRAINT FK_1AC37BD246690F40');
        $this->addSql('ALTER TABLE notification_service DROP CONSTRAINT FK_F4831065EF1A9D84');
        $this->addSql('ALTER TABLE notification_tour DROP CONSTRAINT FK_D2EDB253EF1A9D84');
        $this->addSql('ALTER TABLE notification_tour_template DROP CONSTRAINT FK_5B2D8C79EF1A9D84');
        $this->addSql('ALTER TABLE destination DROP CONSTRAINT FK_3EC63EAAE946114A');
        $this->addSql('ALTER TABLE notification_service DROP CONSTRAINT FK_F4831065ED5CA9E6');
        $this->addSql('ALTER TABLE tour DROP CONSTRAINT FK_6AD1F969ED5CA9E6');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDEAE2DDF69');
        $this->addSql('ALTER TABLE srroom_type DROP CONSTRAINT FK_F7287958AE2DDF69');
        $this->addSql('ALTER TABLE booking DROP CONSTRAINT FK_E00CEDDE15ED8D43');
        $this->addSql('ALTER TABLE booking_transfer DROP CONSTRAINT FK_7B003D4D15ED8D43');
        $this->addSql('ALTER TABLE itinerary DROP CONSTRAINT FK_FF2238F615ED8D43');
        $this->addSql('ALTER TABLE notification_tour DROP CONSTRAINT FK_D2EDB25315ED8D43');
        $this->addSql('ALTER TABLE tour_activity DROP CONSTRAINT FK_368B506915ED8D43');
        $this->addSql('ALTER TABLE itinerary_template DROP CONSTRAINT FK_B6822B42658C5D7B');
        $this->addSql('ALTER TABLE notification_tour_template DROP CONSTRAINT FK_5B2D8C79658C5D7B');
        $this->addSql('ALTER TABLE tour DROP CONSTRAINT FK_6AD1F9695DA0FB8');
        $this->addSql('ALTER TABLE tour_template DROP CONSTRAINT FK_D9F46B013D3CC22');
        $this->addSql('ALTER TABLE tour_template DROP CONSTRAINT FK_D9F46B016663CC');
        $this->addSql('ALTER TABLE tour_template_activity DROP CONSTRAINT FK_803C52C6658C5D7B');
        $this->addSql('ALTER TABLE tour DROP CONSTRAINT FK_6AD1F969F7BB88E4');
        $this->addSql('ALTER TABLE tour_template DROP CONSTRAINT FK_D9F46B0F7BB88E4');
        $this->addSql('ALTER TABLE transportation_price DROP CONSTRAINT FK_D2CF7972F7BB88E4');
        $this->addSql('ALTER TABLE transportation_route DROP CONSTRAINT FK_1AC37BD2F7BB88E4');
        $this->addSql('DROP SEQUENCE activity_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE activity_combo_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE booking_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE booking_accommodation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE booking_house_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE booking_house_room_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE booking_transfer_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE destination_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE driver_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE guide_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE house_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE house_feature_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE house_room_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE house_room_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE house_season_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE house_season_room_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE house_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE itinerary_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE itinerary_day_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE itinerary_day_template_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE itinerary_template_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE location_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE location_distance_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE notification_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE notification_tour_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE notification_tour_template_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE province_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE service_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE sleeping_requirement_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE srroom_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tour_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tour_template_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE transportation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE transportation_price_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE transportation_route_id_seq CASCADE');
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE activity_combo');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE booking_accommodation');
        $this->addSql('DROP TABLE booking_house');
        $this->addSql('DROP TABLE booking_house_room');
        $this->addSql('DROP TABLE booking_transfer');
        $this->addSql('DROP TABLE booking_transfer_house');
        $this->addSql('DROP TABLE destination');
        $this->addSql('DROP TABLE driver');
        $this->addSql('DROP TABLE guide');
        $this->addSql('DROP TABLE house');
        $this->addSql('DROP TABLE house_house_feature');
        $this->addSql('DROP TABLE house_feature');
        $this->addSql('DROP TABLE house_room');
        $this->addSql('DROP TABLE house_room_type');
        $this->addSql('DROP TABLE house_season');
        $this->addSql('DROP TABLE house_season_room');
        $this->addSql('DROP TABLE house_type');
        $this->addSql('DROP TABLE itinerary');
        $this->addSql('DROP TABLE itinerary_day');
        $this->addSql('DROP TABLE itinerary_day_activity');
        $this->addSql('DROP TABLE itinerary_day_template');
        $this->addSql('DROP TABLE itinerary_day_template_activity');
        $this->addSql('DROP TABLE itinerary_template');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE location_distance');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE notification_service');
        $this->addSql('DROP TABLE notification_tour');
        $this->addSql('DROP TABLE notification_tour_template');
        $this->addSql('DROP TABLE province');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE sleeping_requirement');
        $this->addSql('DROP TABLE srroom_type');
        $this->addSql('DROP TABLE tour');
        $this->addSql('DROP TABLE tour_activity');
        $this->addSql('DROP TABLE tour_template');
        $this->addSql('DROP TABLE tour_template_activity');
        $this->addSql('DROP TABLE transportation');
        $this->addSql('DROP TABLE transportation_price');
        $this->addSql('DROP TABLE transportation_route');
    }
}
